### ISSUE TITLE
cudnn-8.0-linux-x64-v5.1.tgz

### ISSUE THREAD

**Issue by codybushnell** [leestott/AzureGPU#1]
Missing wget of cudnn-8.0-linux-x64-v5.1.tgz. Looks like it used to be hosted at a Stanford file server?

Ended up finding it here.

https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v5.1/prod_20161129/8.0/cudnn-8.0-linux-x64-v5.1-tgz

Note: I had to make a developer account with nvidia, download it locally, then push to the vm over SFTP. Assuming wget won't work with the link since you need to have a dev account, but didn't try it.

**Comment by leestott** [comment]
Hi I have included the file in the repo now
